version: '3.8'

services:
  pingplotter:
    image: netsaver/pingplotter:latest
    container_name: pingplotter
    ports:
      - "9911:9911"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9911/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Privileged mode may be required for traceroute on some systems
    # cap_add:
    #   - NET_RAW
    #   - NET_ADMIN
